version: "3.9"
services:
  mariadb:
    container_name: mariadb
    networks:
      - inception
    build: 
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    container_name: nginx
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    depends_on:
      - wordpress
    build: 
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - inception
    build: 
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      mariadb:
        condition: service_healthy
    restart: on-failure
    expose: 
      - "9000"
    # ports:
    # - 9001:9001

  adminer:
    image: adminer
    container_name: adminer
    networks:
      - inception
    restart: on-failure
    ports:
      - 8080:8080
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    networks:
      - inception
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    restart: unless-stopped
    ports:
      # - 9000:9000 # http
      - 9443:9443 # https

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/jvacaris/data/wordpress'

  portainer:
    name: portainer
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/jvacaris/data/portainer'

  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: '/Users/jvacaris/data/mariadb'

networks:
  inception:
    driver: bridge