CREATE DATABASE IF NOT EXISTS `$MYSQL_SERVER_NAME`;
CREATE USER IF NOT EXISTS `$MYSQL_USER`@'localhost' IDENTIFIED BY '$MYSQL_PASSWORD';
GRANT ALL PRIVILEGES ON `$MYSQL_SERVER_NAME`.* TO `$MYSQL_USER`@'%' IDENTIFIED BY '$MYSQL_PASSWORD';
ALTER USER 'root'@'localhost' IDENTIFIED BY '$MYSQL_ROOT_PASSWORD';
FLUSH PRIVILEGES;

